---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-r-markdown-templates/svm-latex-cv.tex
geometry: margin=1in

title: "Curriculum Vitae"
author: Kathleen Ellen Wendt

jobtitle: "NSF Graduate Research Fellow | CSU Graduate Fellow | Graduate Student"
address: "Behavioral Sciences Building 438/439 · Colorado State University  · Fort Collins, CO"
fontawesome: yes
email: Kathleen.Wendt@colostate.edu
github: wendtke
twitter: wendtke
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Education

National Science Foundation Graduate Research Fellow \hfill 2018 - 2023

*Colorado State University*, Ph.D. in Applied Developmental Science \hfill Expected 2023

*Colorado State University*, M.S. in Prevention Science \hfill Expected 2020

*Colorado State University*, B.S. in Human Development and Family Studies \hfill 2018

\hfill University Honors Scholar & *Summa Cum Laude*


# Research Experience

**Mindfulness and Family Resilience Laboratory** (MFR), Lab Manager \hfill  2016 - Present

Director & Principal Investigator: J. Douglas Coatsworth, Ph.D.

Project administration; data collection using complex physiological and observational equipment; data analysis via dynamic systems-based methods and modeling; technical and scientific writing; R programming; recruitment, training, mentorship, and management of 10+ undergraduate research assistants

## Current Studies

1. *Mindful Parent Observational Study* (MPOS): Code and analyze behavioral and affective indicators in structured parent-youth interactions as part of randomized controlled trial of the Mindfulness-enhanced Strengthening Families Program (MSFP)

2. *Project Mind-Heart* (PMH): Investigate effects of brief mindfulness induction on individual and dyadic patterns of physiological, affective, and behavioral indicators during challenging parent-child interactions

**Parenting Young Children Project** (NICHD), Project Manager \hfill 2015 - 2018

Principal Investigator: Erika S. Lunkenheimer, Ph.D.

Project management, grant administration, participant recruitment and retention, technical and scientific writing, and data collection and analysis using dynamic systems-based methods and modeling for NIH-funded longitudinal study investigating parents’ and young children’s (2.5 to 4 years old) dyadic coordination of emotions, behaviors, and physiology and associated risk of child maltreatment and psychopathology

**Child Trauma and Resilience Assessment Center**, Intern \hfill Fall 2017

Principal Investigator: Lise Youngblade, Ph.D.

Director: Stephanie Seng, M.S.

Administrative and research support for SAMHSA-funded projects focused on state-wide trauma-informed training, development of adult trauma assessment, and trauma assessment provision for high-risk adolescents

**Cognitive Neuroimaging Laboratory**, Honors Undergraduate Research Scholar \hfill 2014 - 2015

Director & Principal Investigator: Carol A. Seger, Ph.D. 

Data collection (within undergraduate psychology research pool) and subsequent data processing for disseration research concerning learning and memory

# Translational Research Experience

**SOS Outreach**, Research Consultant \hfill 2019 - Present

Principal Investigator: J. Douglas Coatsworth, Ph.D. 

Executive Director: Seth Erhlich 

Qualitative and quantitative data management and analysis; study design and planning; grant-writing to help bolster research-base for outdoor-based  mentorship and leadership program for at-risk and marginalized youth

**Douglas County CSU Extension Office**, Program Evaluator \hfill 2019 - Present

Principal Investigator: David MacPhee, Ph.D. 

Program Director: Kyle Christensen

Evaluate efficacy and effectiveness of Youth Leadership Summit (October 17-21 2019) serving diverse Colorado youth.

# Peer-Reviewed Publications

## Under Review

Skoranski, A.M., Lunkenheimer, E.S., & **Wendt, K.E.**. Flexible or inconsistent? The impact of parent-child dyadic flexibility on child emotion regulation varies by maternal depressive symptoms. Manuscript under review.

## In Preparation

Prendergast, S., Miller, R., **Wendt, K.E.**, Gerst, K., Klinedinst, T., Prince, M. Multimorbidity and limitations in daily living in Medicare beneficiaries: A comparsion of big data modeling approaches. Manuscript in preparation.

Coatsworth, J.D., **Wendt, K.E.**, Lunkenheimer, E.S., & Cleavinger, E.J. Effects of brief mindfulness induction on parents' autonomic mode during challenging parent-child interactions. Manuscript in preparation.

**Wendt, K.E.**, Coatsworth, J.D., Lunkenheimer, E.S., & Cleavinger, E.J. Individual moderators of brief mindfulness induction on parents' autonomic mode. Manuscript in preparation.

Biedermann, A., Coatsworth, J.D., **Wendt, K.E.**, & Lunkenheimer, E.S. Effects of brief mindfulness induction on parents' mood regulation during challenging parent-child interactions.


# Presentations

**Wendt, K.E.**, Zhang, S., Feldman, M.J., Anderson, G.B., & Coatsworth, J.D. (2019, November). `psyphr.read`: R package to wrangle and tidy psychophysiological data from proprietary systems. Abstract under review for the Graduate Student Showcase, Colorado State University, Fort Collins, CO.

Prendergast, S., Miller, R., **Wendt, K.E.**, Klinedinst, T., & Gerst, K. (2019, May). Informing precision prevention using latent class analysis. Presentation in the Sloboda & Bukoski Cup at the Society for Prevention Research Annual Meeting, San Francisco, CA.

**Wendt, K.E.**, Coatsworth, J.D., Lunkenheimer, E.S., & Cleavinger, E.J. (2019, May). Effects of mindfulness induction on parents' parasympathetic activity in parent-child interactions. Poster presented at Society for Prevention Research Annual Meeting, San Francisco, CA.

Toll, R., George, M.R., Duey, S., Nichols, K., Riggs, N.R., & **Wendt, K.E.** (2018, May). Promoting innovation in prevention science. Special Interest Group at Society for Prevention Research Annual Meeting, Washington, D.C.

**Wendt, K.E.** & Coatsworth, J.D. (2018, April). Exploring moderators of mindfulness training on parental physiological regulation and mood. Paper presented at Celebrate Undergraduate Research and Creativity Showcase, Colorado State University, Fort Collins, CO.

**Wendt, K.E.**, Skoranski, A.M., & Lunkenheimer, E.S. (2017, April). Maternal depression moderates the relationship between mother-child coregulation and child emotion regulation. Poster presented at Celebrate Undergraduate Research and Creativity Showcase, Colorado State University, Fort Collins, CO.


# Software Development

**Wendt, K.E.**, Zhang, S, Feldman, M.F., Anderson, G.B. (2019). `psyphr`: R package suite to wrangle, visualize, and analyze psychophysiological data. In active development.

# Honors & Awards

## Graduate

- RStudio Travel Award for R/Pharma \hfill 2019
- R/Pharma Travel Award \hfill 2019
- Pearl E. Betts Graduate Scholarship \hfill 2019
- HDFS Department Travel Grant (Society for Prevention Research) \hfill 2019
- SPR Early Career Preventionist Network (ECPN) Travel Award \hfill 2019
- Uncoast Unconf Travel Grant \hfill 2019
- CSU Graduate School Travel Grant (Uncoast Unconf) \hfill 2019
- Departmental Travel Grant (Uncoast Unconf) \hfill 2019
- Colorado State University Graduate Fellowship \hfill 2018
- National Science Foundation Graduate Research Fellowship \hfill 2018 - 2023

## Undergraduate

- College of Health & Human Sciences Outstanding Graduate \hfill 2018
- Albert C. and Ann E. Yates Pacesetter Scholarship \hfill 2017
- Anne Blair Scholarship \hfill 2017
- College of Health and Human Sciences Students First Scholarship \hfill 2016
- Spots Scholarship \hfill 2015
- Honors Scholarship \hfill 2014 - 2018
- Green & Gold Scholarship \hfill 2014 - 2018


# Professional Membership

- Society for Prevention Research (SPR) \hfill 2018 - Present
- SPR Early Career Preventionist Network (ECPN) \hfill 2018 - Present
- European Society for Prevention Research (EUSPR) \hfill 2018 - Present
- EUSPR Early Career Forum (ECF) \hfill 2018 - Present


# Teaching & Mentoring Experience

**Colorado State University** \hfill 2018 - Present

- Graduate School and Fellowship Application Mentor

**HDFS Department**, Colorado State University \hfill  Fall 2016

- Undergraduate Teaching Assistant for Infant & Child Development 

**Office of International Programs**, Colorado State University \hfill  2016

- Exchange Student Mentor

**African Impact & Colorado State University**, Livingstone, Zambia \hfill  Summer 2015

- Teaching Volunteer


# Service

## Professional

**Society for Prevention Research** (SPR) \hfill 2018 - Present

- Abstract Student-Reviewer
- Symposuium Moderator
 
**SPR Early Career Preventionist Network** (ECPN) \hfill 2018 - Present

- Steering Committee Member (2018 - Present)
- Awards Subcommittee Member (2018 - 2019)
- Program Subcommittee Member (2019 - 2020)

**European Society for Prevention Research** (EUSPR) \hfill 2018 - Present

- Abstract Student-Reviewer


## University & Department

**Graduate Student Council** (GSC), Colorado State University \hfill 2018 - Present

- Department Representative 
- Travel Award Reviewer

***Journal of Undergraduate Research***, Colorado State University  \hfill 2018 - Present

- Graduate Referee

**The Graduate School**, Colorado State University

- Reviewer - NSF GRFP Writing Workshop \hfill October 2, 2018
- Panelist - NSF GRFP Informational Session \hfill August 28, 2018

**Department of Human Development and Family Studies** (HDFS) \hfill 2019 - Present

- Speaker Series Coordinator 


## Community 

**Center for Public Deliberation** \hfill 2016 - Present

- Community Associate

Director: Martín Carcasson, Ph.D.

**Kids at Heart**, Fort Collins & Loveland, CO \hfill  2014 - 2017

- Group Leader  

**Pathways Hospice and Palliative Care**, Fort Collins, CO \hfill  2016

- Volunteer 


# Computer Skills

- R language and extras (e.g., RStudio, R Markdown, Shiny)
- Git and GitHub
- SPSS (although I actively avoid using it)


# Professional Development Activities

- R/Pharma conference \hfill August 21-23, 2019
- Uncoast Unconf with R \hfill April 14-16, 2019
- NIH Grant-Writing Workshop, Dr. Maria Esformes \hfill August 3, 2018
- Heart Rate Variability Seminar, Dr. Gary Berntson \hfill June 9-10, 2018
- Bayesian Causal Mediation Analysis Workshop, Dr. David MacKinnon et al. \hfill May 29, 2018
- Mental Health-Education Integration Consortium (MHEDIC) \hfill May 3-4, 2018
