---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-r-markdown-templates/svm-latex-cv.tex
geometry: margin=1in

title: "Curriculum Vitae"
author: Kathleen Ellen Wendt

jobtitle: "NSF Graduate Research Fellow | Graduate Student"
address: "Behavioral Sciences Building · Colorado State University  · Fort Collins, CO"
fontawesome: yes
email: Kathleen.Wendt18@alumni.colostate.edu
github: wendtke
twitter: wendtke
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: red
urlcolor: red
---

# Education

[National Science Foundation Graduate Research Fellowship Program](https://www.nsfgrfp.org/) \hfill 2018 - Present

- Graduate Research Fellowship in Developmental Psychology \hfill 2018 - Present

[Colorado State University](https://www.colostate.edu/) (CSU) \hfill 2014 - Present

- M.S. in [Prevention Science](https://www.chhs.colostate.edu/hdfs/programs-and-degrees/m-s-in-human-development-and-family-studies/prevention-science-specialization/) \hfill Expected December 2020

- Graduate Certificate in [Data Analysis](https://statistics.colostate.edu/graduate-certificate-in-data-analysis/#:~:text=The%20Graduate%20Certificate%20in%20Data,will%20strengthen%20their%20statistical%20skills.) \hfill 2020

- B.S. in [Human Development and Family Studies](https://www.chhs.colostate.edu/hdfs/programs-and-degrees/b-s-in-human-development-and-family-studies/) (*summa cum laude*) \hfill 2018

  - Minor in [International Development Studies](https://international.colostate.edu/global-engagement/international-development-studies/) \hfill 2018

  - Concentration in [Prevention and Intervention Science](https://catalog.colostate.edu/general-catalog/colleges/health-human-sciences/human-development-family-studies/human-development-family-studies-major-prevention-intervention-sciences-concentration/) \hfill 2018

# Research Experience

**[Mindfulness and Family Resilience Laboratory](https://www.chhs.colostate.edu/hdfs/research/research-labs/mindfulness-and-family-resilience-lab/)** (MFR), Lab Manager \hfill  2016 - Present

Director & Principal Investigator: J. Douglas Coatsworth, Ph.D.

Purpose: Investigate use and benefits of mindfulness in family contexts

- *Project Mind-Heart* (PMH): Investigate effects of brief mindfulness induction on individual and dyadic patterns of physiological, affective, and behavioral indicators during challenging parent-child interactions

- *Mindful Parent Observational Study* (MPOS): Analyze behavioral and affective indicators of mindfulness and interaction quality in structured parent-youth interactions as part of randomized controlled trial of the Mindfulness-enhanced Strengthening Families Program (MSFP)

Tasks: Project administration, planning, and management; data collection with physiological and observational systems; R programming; data analysis; technical, scientific, and grant writing; recruitment, training, mentorship, and management of 10+ undergraduate research assistants

- Funding: CSU Prevention Research Center

**[Parent-Child Dynamics Laboratory](https://pcd.la.psu.edu/)**, Project Manager \hfill 2015 - 2018

Director & Principal Investigator: Erika S. Lunkenheimer, Ph.D.

Purpose: Study how parenting and parent-child interactions influence child development in high-stress families

- *Parenting Young Children Project* (PYCP): Test parents’ and young children’s dyadic coordination of emotions, behaviors, and physiology and associated risk of child maltreatment and psychopathology

  - Tasks: Project management, grant administration, participant recruitment and retention, technical and scientific writing, and data collection, management, and processing with physiological and observational systems

  - Grant Funding: Eunice Kennedy Shriver National Institute of Child Health and Development Career Development Award (K01) to PI Lunkenheimer 

**Child Trauma and Resilience Assessment Center**, Intern \hfill Fall 2017

Principal Investigator: Lise Youngblade, Ph.D.

Director: Stephanie Seng, M.S.

- Tasks: Administrative and research support for SAMHSA- and DHS-funded projects focused on state-wide trauma-informed training, development of adult trauma assessment, and trauma assessment provision for high-risk adolescents

- Grant Funding: Substance Abuse and Mental Health Services Colorado Children's Congregate Care Resiliency Opportunity Project (CROP) to PI Youngblade

**Cognitive Neuroimaging Laboratory**, Honors Undergraduate Research Scholar \hfill 2014 - 2015

Principal Investigator: Carol A. Seger, Ph.D.

- Data collection, processing, and management for dissertation research on learning and memory

# Translational Research Experience

**Douglas County CSU Extension Office**, Program Evaluator \hfill 2019 - 2020

Principal Investigator: David MacPhee, Ph.D. 

Program Director: Kyle Christensen

- Evaluate program implementation of Youth Leadership Summit (October 18-20, 2019) for diverse Colorado youth

**SOS Outreach**, Research Consultant (*pro bono*) \hfill 2019 

Principal Investigator: J. Douglas Coatsworth, Ph.D. 

Executive Director: Seth Erhlich 

- Tasks: Qualitative and quantitative data management and analysis, study design and planning, R programming consultation for Shiny dashboard development, and grant-writing to help bolster research-base for outdoor-based mentorship and leadership program for at-risk and marginalized youth

# Teaching Experience

**CSU Department of Mechanical Engineering**, Teaching Assistant \hfill 2020 - Present

Instructor: John Volckens, Ph.D.

- Develop curricula for and assist with implementation of open-source, upper-division undergraduate engineering data analysis course in R

**CSU Department of Statistics**, Course Developer \hfill 2020 - Present

Co-Principal Investigators: Matthew V. Ross, Ph.D. & Ben Prytherch, M.S.

Instructor: Alex Fout, M.S.

- Develop curricula for online, open-source introductory programming and statistical computing course in R

- Grant Funding: CSU Provost Office Digital Learning Initiative 

**useR! 2020 Conference**, Teaching Assistant (*pro bono*) \hfill July 2020

Instructor: Samantha Tyner, Ph.D.

- Help develop and execute online tutorial for data visualization 

**Department of Human Development and Family Studies**, Teaching Assistant \hfill  Fall 2016

Instructor: Erika S. Lunkenheimer, Ph.D.

- Grading and exam review sessions for upper-division undergraduate course on infant and child development

# Software Development

**Wendt, K.E.**, Zhang, S., Feldman, M.F., & Anderson, G.B. (2019). [`psyphr`](https://github.com/psyphr-dev): R package suite to wrangle, filter, visualize, analyze, and share physiological data. In active development.

# Peer-Reviewed Publications

## Under Review

Lunkenheimer, E.S., Skoranski, A.M., & **Wendt, K.E.** Flexible or inconsistent? Parental depressive symptoms and parent-child behavioral
inconsistency heighten child dysregulation. Manuscript under review.

## In Preparation

**Wendt, K.E.**, Lucas-Thompson, R.G., Lunkenheimer, E.S., & Coatsworth, J.D. The effects of a brief mindfulness induction on parents' autonomic activity during challenging parent-child interactions. Manuscript in preparation.

Grant, S.P., **Wendt, K.E.**, Gardner, F., Leadbeater, B.J., Crowley, D.M., Mayo-Wilson, E., Supplee, L.H., & Bradshaw, C.P. Transparent, open, and reproducible prevention science. Anchoring statement for 2020 Special Issue of *Prevention Science*. Manuscript in preparation.

**Wendt, K.E.**, Timpe, Z.C., Anderson, G.B, Chorpita, B.F., & Coatsworth, J.D. The promise of open source and open access: Computational reproducibility and knowledge management in prevention science. Invited manuscript submission for 2020 Special Issue of *Prevention Science*. Manuscript in preparation.

Prendergast, S., Klinedinst, T., Miller, R.L., Gerst, K., & **Wendt, K.E.**. Multiple chronic conditions and functional decline among Medicare beneficiaries: A comparison of modeling approaches. Manuscript in preparation.

# Presentations

**Wendt, K.E.**, Zhang, S., Feldman, M.J., Anderson, G.B., & Coatsworth, J.D. (2019, November). `psyphr.read`: R package to wrangle and tidy psychophysiological data from proprietary systems. Poster presentation at the Graduate Student Showcase, Colorado State University, Fort Collins, CO.

Prendergast, S., Miller, R., **Wendt, K.E.**, Klinedinst, T., & Gerst, K. (2019, May). Informing precision prevention using latent class analysis. Presentation in the Sloboda & Bukoski Cup at the Society for Prevention Research Annual Meeting, San Francisco, CA.

**Wendt, K.E.**, Coatsworth, J.D., Lunkenheimer, E.S., & Cleavinger, E.J. (2019, May). Effects of mindfulness induction on parents' parasympathetic activity in parent-child interactions. Poster presented at Society for Prevention Research Annual Meeting, San Francisco, CA.

Toll, R., George, M.R., Duey, S., Nichols, K., Riggs, N.R., & **Wendt, K.E.** (2018, May). Promoting innovation in prevention science. Special Interest Group at Society for Prevention Research Annual Meeting, Washington, D.C.

# Honors & Awards

## Graduate

- useR! Diversity Scholarship for useR! Conference \hfill 2020
- RStudio Diversity Scholarship for RStudio Conference \hfill 2020
- Departmental Travel Grant for RStudio Conference \hfill 2020
- RStudio Travel Award for R/Pharma \hfill 2019
- R/Pharma Travel Award (B2S Life Sciences) \hfill 2019
- Pearl E. Betts Graduate Scholarship \hfill 2019
- Departmental Travel Grant for Society for Prevention Research \hfill 2019
- SPR Early Career Preventionist Network (ECPN) Travel Award \hfill 2019
- Uncoast Unconf Travel Grant \hfill 2019
- CSU Graduate School Travel Grant for Uncoast Unconf \hfill 2019
- Departmental Travel Grant for Uncoast Unconf \hfill 2019
- Colorado State University Graduate Fellowship \hfill 2018
- National Science Foundation Graduate Research Fellowship \hfill 2018 - 2023

## Undergraduate

- University Honors Scholar \hfill 2018
- College of Health & Human Sciences Outstanding Graduate \hfill 2018
- Albert C. and Ann E. Yates Pacesetter Scholarship \hfill 2017
- Anne Blair Scholarship \hfill 2017
- College of Health & Human Sciences Students First Scholarship \hfill 2016
- Spots Scholarship \hfill 2015
- Honors Scholarship \hfill 2014 - 2018
- Green & Gold Scholarship \hfill 2014 - 2018

# Computer Skills

- R and its extensions (e.g., RStudio, R Markdown, Shiny)
- Version control and collaboration with Git/GitHub
- Python (currently learning)
- SPSS (although I actively avoid using it)
- Microsoft Office Suite
- Collaborative clouds including Google Drive and OneDrive

# Professional Development Activities

- useR! Conference (online due to COVID-19) \hfill July 2020
- RStudio `tidyverse` developer day - Dr. Hadley Wickham \hfill January 31, 2020
- RStudio Conference \hfill January 29-30, 2020
- RStudio `tidy tools` workshop - Drs. Hadley & Charlotte Wickham \hfill January 27-28, 2020
- R/Pharma conference \hfill August 22-23, 2019
- R/Pharma `plotly` workshop - Dr. Carson Sievert \hfill August 21, 2019
- Uncoast Unconf with R \hfill April 14-16, 2019
- Grant-Writing Workshop for NIH - Dr. Maria Esformes \hfill August 3, 2018
- Heart Rate Variability Workshop - Dr. Gary Berntson \hfill June 9-10, 2018

# Professional Membership

- Society for Prevention Research (SPR)
- SPR Early Career Preventionist Network (ECPN) 
- European Society for Prevention Research (EUSPR) 
- EUSPR Early Career Forum (ECF)

# Service

## Professional

**rOpenSci** \hfill 2019 - Present

- R Package Reviewer

**Society for Prevention Research** (SPR) \hfill 2018 - 2020

- Abstract Student-Reviewer
- Symposium Moderator
 
**SPR Early Career Preventionist Network** (ECPN) \hfill 2018 - Present

- Steering Committee Member (2018 - Present)
- Program Subcommittee Member (2019 - 2020)
- Awards Subcommittee Member (2018 - 2019)

**European Society for Prevention Research** (EUSPR) \hfill 2018 - 2019

- Abstract Reviewer

## University & Department

***Journal of Undergraduate Research***, Colorado State University  \hfill 2018 - 2020

- Graduate Referee

**Graduate Student Council** (GSC), Colorado State University \hfill 2018 - 2020

- Department Representative 
- Travel Award Reviewer

**The Graduate School**, Colorado State University

- Reviewer - NSF GRFP Writing Workshop \hfill 2018, 2019
- Panelist - NSF GRFP Informational Session \hfill 2018, 2019

**Department of Human Development and Family Studies** (HDFS) \hfill 2019

- Speaker Series Coordinator 
- Panelist - HDFS Graduate Programs Informational Sessions 
